from itertools import product
import json
import random
import numpy as np
import pytest
from umtc import load_json
from qsl_classification import classify,eta_from_json
from qsl_classification.groups import SpaceGroup,Intrinsic
from qsl_classification.algebra import AnyonModule,CohomologyQuotient
from qsl_classification.extensions import ExtensionCollector


@pytest.mark.parametrize('n,mirror',list(product((4,6),(False,True))))
def test_infinite_group_associativity(n,mirror):
    s = SpaceGroup(n,mirror)
    rng = random.Random(15)
    for _ in range(50):
        gs = [s.element(rng.randrange(-100,100),rng.randrange(-100,100),rng.randrange(n),
                        rng.randrange(2) if mirror else 0,rng.randrange(2) if mirror else 0) for _ in range(3)]
        a,b,c = gs
        assert s.multiply(a,s.multiply(b,c)) == s.multiply(s.multiply(a,b),c)


@pytest.mark.parametrize('name,group', [('u1_4','p4*SO(3)'),('u1_6','p6*SO(3)'),
                                     ('z2_gauge','p4m*O(3)'),('z3_gauge','p6m*O(3)')])
def test_twisted_cocycles_on_signed_translations(examples,name,group):
    cat = load_json(examples/(name+'.json')); intr=Intrinsic(cat); module=AnyonModule(cat,intr)
    s=SpaceGroup.parse(group); rng=random.Random(273)
    for hom in intr.homomorphisms(s):
        e=ExtensionCollector(s,module,intr,hom);q=e.cohomology()
        coords=np.array([rng.randrange(m) for m in q.orders],dtype=np.int64)
        v=q.lifts@coords
        def t(g,h):
            return e.cocycle_matrix(g,h)@v
        for _ in range(8):
            g,h,k=[s.element(rng.randrange(-8,8),rng.randrange(-8,8),rng.randrange(s.n),
                              rng.randrange(2) if s.mirror else 0,rng.randrange(2) if s.mirror else 0)
                   for _ in range(3)]
            residual=module.actions[intr.word(hom,g)]@t(h,k)+t(g,s.multiply(h,k))-t(g,h)-t(s.multiply(g,h),k)
            assert not np.any(residual%np.array(module.moduli))


def test_mixed_modulus_quotient_against_exhaustive_enumeration():
    # V=Z2×Z4×Z6, C(x)=2x0+x1 mod4; B generated by (1,2,0).
    mods=(2,4,6)
    C=np.array([[2,1,0]])
    B=np.array([[1],[2],[0]])
    q=CohomologyQuotient(mods,C,[4],B)
    kernel=[x for x in product(*(range(m) for m in mods)) if not (C@x)[0]%4]
    keys={q.project(x) for x in kernel}
    assert len(keys)==q.size==6
    for x in kernel:
        assert q.project(x)==q.project((np.array(x)+B[:,0])%mods)


def test_json_and_unbounded_eta(examples):
    p=examples/'u1_2.json'
    r=classify('p4*SO(3)',['1 a'],p,verbose=True)
    assert r['total_realizations']==1
    r=json.loads(json.dumps(r))
    eta=eta_from_json(r['homomorphisms'][0]['realizations'][0]['eta_symbol'],p)
    X={'spin':[0,1,0,0]}
    assert abs(eta([1],X,X)+1)<1e-8
    assert abs(eta([1],{'spin':[0,-1,0,0]},X)+1)<1e-8
    huge=(10**40,-10**35,3)
    assert abs(abs(eta((1,),huge,(-10**30,10**50,2)))-1)<1e-8


def test_invalid_inputs(examples):
    p=examples/'u1_2.json'
    for group,iwps in [('p7*SO(3)',[]),('p6*SO(3)',['1 b']),('p4*SO(3)',['3 c'])]:
        with pytest.raises(ValueError):classify(group,iwps,p)
    assert classify('p6*SO(3)',['2 b'],p)['total_realizations']==5
    assert classify('p4*SO(3)',['1 a','1 a'],p)['total_realizations']==9
    assert classify('p4m*O(3)',[],p)['number_of_homomorphisms']==0


def test_extra_order_three_class_is_retained(examples):
    c=load_json(examples/'u1_6.json');intr=Intrinsic(c);module=AnyonModule(c,intr)
    e=ExtensionCollector(SpaceGroup(6),module,intr,('1','1','C'))
    q=e.cohomology()
    assert q.size==24
    assert q.orders==(2,2,6)
    # Tails (b,c,d,r,s)=(0,0,2,0,0), a nonzero order-three class.
    x=np.array([0,0,2,0,0])
    assert any(q.project(x))
    assert not any(q.project(3*x))


def test_relabeling_and_chiral_results(examples):
    r=classify('p4*SO(3)',[],examples/'u1_4.json')
    assert [h['number_of_realizations'] for h in r['homomorphisms']]==[24,12,20,20]
    r=classify('p4*SO(3)',[],examples/'su2_k6.json')
    assert r['total_realizations']==64
    assert all(h['number_of_realizations']==16 for h in r['homomorphisms'])


def test_mirror_reference_counts(examples):
    assert classify('p6m*O(3)',[],examples/'z2_gauge.json')['total_realizations']==336
    assert classify('p6m*O(3)',['1 a'],examples/'z2_gauge.json')['total_realizations']==8
    assert classify('p4m*O(3)',[],examples/'double_semion.json')['total_realizations']==128


def test_category_name_does_not_select_algorithm(examples,tmp_path):
    data=json.loads((examples/'u1_2.json').read_text())
    data['name']='Unrecognized category name'
    path=tmp_path/'unknown.json';path.write_text(json.dumps(data))
    assert classify('p4*SO(3)',[],path)['total_realizations']==9


def test_all_catalog_files_are_in_paper_suite_or_fibonacci(examples):
    import importlib.util
    from pathlib import Path
    path=Path(__file__).resolve().parents[1]/'scripts/validate_papers.py'
    spec=importlib.util.spec_from_file_location('references',path)
    mod=importlib.util.module_from_spec(spec);spec.loader.exec_module(mod)
    reference_cases=list(mod.references())
    names={row[0] for row in reference_cases}|{'fibonacci'}
    assert names=={f.stem for f in examples.glob('*.json')}
    runner_path=Path(__file__).resolve().parents[1]/'run_examples.py'
    spec=importlib.util.spec_from_file_location('example_runner',runner_path)
    runner=importlib.util.module_from_spec(spec);spec.loader.exec_module(runner)
    example_cases=[(name,group,lattice,tuple(iwps))
                   for name,groups in runner.example_groups() for group in groups
                   for lattice,iwps in runner.lattice_cases(group)]
    assert len(example_cases)==len(set(example_cases))==276
    assert set(example_cases)=={(name,group,lattice,tuple(iwps))
                               for name,group,lattice,iwps,*_ in reference_cases}
    for group in ('p4*SO(3)','p6*SO(3)','p4m*O(3)','p6m*O(3)'):
        r=classify(group,[],examples/'fibonacci.json')
        assert r['total_realizations']==int('m*' not in group)
